language: android
dist: trusty
sudo: false
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - android-29
    - build-tools-29.0.3
    - platform-tools
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - "${TRAVIS_BUILD_DIR}/gradle/caches/"
    - "${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/"
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
before_script:
  - chmod +x gradlew
script:
  - ./gradlew build --stacktrace

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/upload-app.sh